#!/bin/env sh

echo TEST $0 running...

export prog=$(cat << EOF
typedef struct {
  int a;
  char b;
  char c;
} point;

int main() {
  point a;
  point b;
  a.c;
}
EOF
)
export stdout=$(cat << EOF
ASSEMBLY:
EXTERN       exit
GLOBAL       _start
SETLABEL     _start
INST         DECSP
INSTRELLABEL CALLR main
INST         POPA
INSTLABEL    CALL exit
SETLABEL     main
INST         DECSP
INST         DECSP
INST         DECSP
INST         DECSP
INST         SP_A
INSTHEX2     RAM_B 0x0009
INST         SUM
INST         A_B
INST         rB_AL
INST         PUSHA
INST         INCSP
INST         INCSP
INST         INCSP
INST         INCSP
INST         INCSP
INST         RET
EOF
)
export params="-D com"
export exitcode=0

#./simpleC $params -e "$prog"

./test $0
