#!/bin/env sh

echo TEST $0 running...

export prog=$(cat << EOF
typedef struct {
  int a;
  char b;
  int c;
} A;

typedef struct {
  int a;
  char b;
  char c;
  int d;
} B;

int main() {
  char a[] = {0x20, 0x01, 0x02};
  A b = {1, 0x02, 3};
  B c = {5, 0x01, 0x02, 4};
}
EOF
)
export stdout=$(cat << EOF
ASSEMBLY:
EXTERN       exit
GLOBAL       _start
SETLABEL     _start
INST         DECSP
INSTRELLABEL CALLR main
INST         POPA
INSTLABEL    CALL exit
SETLABEL     main
INSTHEX      RAM_AL 0x02
INST         PUSHA
INSTHEX      RAM_AL 0x20
INSTHEX      RAM_BL 0x01
INST         B_AH
INST         PUSHA
INSTHEX      RAM_AL 0x03
INST         PUSHA
INSTHEX      RAM_AL 0x02
INST         PUSHA
INSTHEX      RAM_AL 0x01
INST         PUSHA
INSTHEX      RAM_AL 0x04
INST         PUSHA
INSTHEX      RAM_AL 0x02
INST         PUSHA
INSTHEX      RAM_AL 0x01
INST         PUSHA
INSTHEX      RAM_AL 0x05
INST         PUSHA
INST         SP_A
INSTHEX2     RAM_B 0x0012
INST         SUM
INST         A_SP
INST         RET
EOF
)
export params="-D com"
export exitcode=0

#./simpleC $params -e "$prog"

./test $0
