#!/bin/env sh

echo TEST $0 running...

export prog=$(cat << EOF
typedef struct {
  int x;
  int y;
} point;

point a[3] = {
  {1, 2},
  {4, 2}
};

int main() {
  a[2];
}
EOF
)
export stdout=$(cat << EOF
ASSEMBLY:
EXTERN       exit
GLOBAL       _start
SETLABEL     _000
HEX2         0x0001
HEX2         0x0002
HEX2         0x0004
HEX2         0x0002
DB           4
SETLABEL     _start
INST         DECSP
INSTRELLABEL CALLR main
INST         POPA
INSTLABEL    CALL exit
SETLABEL     main
INSTLABEL    RAM_A _000
INST         PUSHA
INSTHEX      RAM_AL 0x02
INST         PUSHA
INST         POPA
INST         SHL
INST         SHL
INST         A_B
INST         POPA
INST         SUM
INST         PUSHA
INST         POPB
INSTHEX2     RAM_A 0x0002
INST         SUM
INST         A_B
INST         rB_A
INST         PUSHA
INSTHEX      RAM_AL 0x02
INST         SUB
INST         A_B
INST         rB_A
INST         PUSHA
INST         INCSP
INST         INCSP
INST         RET
EOF
)
export params="-D com"
export exitcode=0

#./simpleC $params -e "$prog"

./test $0
