#!/bin/env sh

echo TEST $0 running...

export prog=$(cat << EOF
int main() {
}
EOF
)
export stdout=$(cat << EOF
ASSEMBLY:
EXTERN       exit
GLOBAL       _start
SETLABEL     _start
INST         DECSP
INSTRELLABEL CALLR main
INST         POPA
INSTLABEL    CALL exit
SETLABEL     main
INST         RET
EOF
)
export params="-D com"
export exitcode=0

# ./simpleC $params -e "$prog"

./test $0
