#!/bin/env sh

export prog=$(cat << EOF
int add(int a) {
  return 2;
}

int main() {
  add(4);
}
EOF
)
export stdout=$(cat << EOF
ASSEMBLY:
EXTERN       exit
GLOBAL       _start
SETLABEL     _start
INST         DECSP
INSTRELLABEL CALLR main
INST         POPA
INSTLABEL    CALL exit
SETLABEL     add
INSTHEX      RAM_AL 0x02
INST         PUSHA
INST         INCSP
INST         INCSP
INST         INCSP
INST         SP_A
INST         A_B
INSTHEX2     RAM_B 0x0004
INST         SUB
INST         A_B
INST         rB_A
INST         PUSHA
INST         DECSP
INST         RET
SETLABEL     main
INSTHEX      RAM_AL 0x04
INST         PUSHA
INST         DECSP
INSTRELLABEL CALLR add
INST         INCSP
INST         INCSP
INST         RET
EOF
)
export params="-D com"
export exitcode=0

# ./simpleC $params -e "$prog"

./test $0

