#!/bin/env sh

echo TEST $0 running...

export prog=$(cat << EOF
int add(int a) {
  return a;
}

int main() {
  add(4);
}
EOF
)
export stdout=$(cat << EOF
ASSEMBLY:
EXTERN       exit
GLOBAL       _start
SETLABEL     _start
INST         DECSP
INSTRELLABEL CALLR main
INST         POPA
INSTLABEL    CALL exit
SETLABEL     add
INSTHEX      PEEKAR 0x06
INST         PUSHA
INST         POPA
INSTHEX      PUSHAR 0x04
INST         RET
SETLABEL     main
INSTHEX      RAM_AL 0x04
INST         PUSHA
INST         DECSP
INSTRELLABEL CALLR add
INST         INCSP
INST         INCSP
INST         RET
EOF
)
export params="-D com"
export exitcode=0

#./simpleC $params -e "$prog"

./test $0

