#!/bin/env sh

export prog=$(cat << EOF
typedef struct {
  int x;
  int y;
} point;

point b[4];

int main() {
  int a[2];

  a[1];
  b[2];
}
EOF
)
export stdout=$(cat << EOF
ASSEMBLY:
EXTERN       exit
GLOBAL       _start
SETLABEL     _000
DB           16
SETLABEL     _start
INST         DECSP
INSTRELLABEL CALLR main
INST         POPA
INSTLABEL    CALL exit
SETLABEL     main
INST         DECSP
INST         DECSP
INST         SP_A
INST         A_B
INSTHEX2     RAM_A 0x0002
INST         SUM
INST         PUSHA
INSTHEX      RAM_AL 0x01
INST         PUSHA
INST         POPA
INST         SHL
INST         A_B
INST         POPA
INST         SUM
INST         PUSHA
INST         POPB
INST         rB_A
INST         PUSHA
INSTLABEL    RAM_A _000
INST         PUSHA
INSTHEX      RAM_AL 0x02
INST         PUSHA
INST         POPA
INST         SHL
INST         SHL
INST         A_B
INST         POPA
INST         SUM
INST         PUSHA
INST         POPB
INSTHEX2     RAM_A 0x0002
INST         SUM
INST         A_B
INST         rB_A
INST         PUSHA
INSTHEX      RAM_AL 0x02
INST         SUB
INST         A_B
INST         rB_A
INST         PUSHA
INST         SP_A
INSTHEX2     RAM_B 0x000C
INST         SUM
INST         A_SP
INST         RET
EOF
)
export params="-D com"
export exitcode=0

#./simpleC $params -e "$prog"

./test $0

