#!/bin/env sh

echo TEST $0 running...

export prog=$(cat << EOF
typedef struct {
  int x;
  int y;
} point;

point b[4] = {
  (point){1,2}
};

int main() {
  int a[2];

  a[1];
  b[2];
}
EOF
)
export stdout=$(cat << EOF
ASSEMBLY:
EXTERN       exit
GLOBAL       _start
SETLABEL     _000
HEX2         0x0001
HEX2         0x0002
DB           12
SETLABEL     _start
INST         DECSP
INSTRELLABEL CALLR main
INST         POPA
INSTLABEL    CALL exit
SETLABEL     main
INST         DECSP
INST         DECSP
INSTHEX      PEEKAR 0x04
INST         PUSHA
INSTHEX2     RAM_A 0x0008
INST         PUSHA
INSTLABEL    RAM_A _000
INST         POPB
INST         SUM
INST         A_B
INSTHEX2     RAM_A 0x0002
INST         SUM
INST         A_B
INST         rB_A
INST         PUSHA
INSTHEX      RAM_AL 0x02
INST         SUB
INST         A_B
INST         rB_A
INST         PUSHA
INST         SP_A
INSTHEX2     RAM_B 0x000A
INST         SUM
INST         A_SP
INST         RET
EOF
)
export params="-D com"
export exitcode=0

#./simpleC $params -e "$prog"

./test $0

