#!/bin/env sh

export prog=$(cat << EOF
typedef struct {
  int x;
  int y;
} point;

point add() {
  point c;
  return c;
}

int main() {
}
EOF
)
export stdout=$(cat << EOF
ASSEMBLY:
EXTERN       exit
GLOBAL       _start
SETLABEL     _start
INST         DECSP
INSTRELLABEL CALLR main
INST         POPA
INSTLABEL    CALL exit
SETLABEL     add
INST         DECSP
INST         DECSP
INST         SP_A
INST         A_B
INSTHEX2     RAM_A 0x0002
INST         SUM
INST         A_B
INSTHEX2     RAM_A 0x0002
INST         SUM
INST         A_B
INST         rB_A
INST         PUSHA
INSTHEX      RAM_AL 0x02
INST         SUB
INST         A_B
INST         rB_A
INST         PUSHA
INST         POPA
INSTHEX      PUSHAR 0x0A
INST         POPA
INSTHEX      PUSHAR 0x0A
INST         INCSP
INST         INCSP
INST         RET
SETLABEL     main
INST         RET
EOF
)
export params="-D com"
export exitcode=0

./simpleC $params -e "$prog"

#./test $0

