#!/bin/env sh

echo TEST $0 running...

export prog=$(cat << EOF
typedef struct {
  int x;
  int y;
} point;

point add() {
  point c;
  return c;
}

int main() {
}
EOF
)
export stdout=$(cat << EOF
ASSEMBLY:
EXTERN       exit
GLOBAL       _start
SETLABEL     _start
INST         DECSP
INSTRELLABEL CALLR main
INST         POPA
INSTLABEL    CALL exit
SETLABEL     add
INST         DECSP
INST         DECSP
INSTHEX      PEEKAR 0x04
INST         PUSHA
INSTHEX      PEEKAR 0x04
INST         PUSHA
INST         POPA
INSTHEX      PUSHAR 0x0A
INST         POPA
INSTHEX      PUSHAR 0x0A
INST         INCSP
INST         INCSP
INST         RET
SETLABEL     main
INST         RET
EOF
)
export params="-D com"
export exitcode=0

#./simpleC $params -e "$prog"

./test $0

