#!/bin/env sh

echo TEST $0 running...

export prog=$(cat << EOF
int a[] = {1, 2, 3};

int *b() {
  return a;
}

int main() {
}
EOF
)
export stdout=$(cat << EOF
ASSEMBLY:
EXTERN       exit
GLOBAL       _start
SETLABEL     _000
HEX2         0x0001
HEX2         0x0002
HEX2         0x0003
SETLABEL     _start
INST         DECSP
INSTRELLABEL CALLR main
INST         POPA
INSTLABEL    CALL exit
SETLABEL     b
INST         INCSP
INST         INCSP
INSTLABEL    RAM_A _000
INST         PUSHA
INST         DECSP
INST         RET
SETLABEL     main
INST         RET
EOF
)
export params="-D com"
export exitcode=0

#./simpleC $params -e "$prog"

./test $0
