#!/bin/env sh

export prog=$(cat << EOF
int main() {
  char *str = "asdf";
  *str;
}
EOF
)
export stdout=$(cat << EOF
ASSEMBLY:
EXTERN       exit
GLOBAL       _start
SETLABEL     _000
STRING       asdf
HEX          0x00
SETLABEL     _start
INST         DECSP
INSTRELLABEL CALLR main
INST         POPA
INSTLABEL    CALL exit
SETLABEL     main
INSTLABEL    RAM_A _000
INST         PUSHA
INSTHEX      PEEKAR 0x02
INST         PUSHA
INST         POPB
INST         rB_AL
INST         PUSHA
INST         INCSP
INST         INCSP
INST         INCSP
INST         RET
EOF
)
export params="-D com"
export exitcode=0

#./simpleC $params -e "$prog"

./test $0
