#!/bin/env sh

echo TEST $0 running...

export prog=$(cat << EOF
typedef struct {
  int x;
  int y;
} point;

int main() {
  point a;
}
EOF
)
export stdout=$(cat << EOF
ASSEMBLY:
EXTERN       exit
GLOBAL       _start
SETLABEL     _start
INST         DECSP
INSTRELLABEL CALLR main
INST         POPA
INSTLABEL    CALL exit
SETLABEL     main
INST         DECSP
INST         DECSP
INST         INCSP
INST         INCSP
INST         RET
EOF
)
export params="-D com"
export exitcode=0

#./simpleC $params -e "$prog"

./test $0

