#!/bin/env sh

export prog=$(cat << EOF
typedef struct {
  int x;
  int y;
} point;

point add(point a, point b) {
  point c;
  return c;
}

int main() {
  point a;
  point b;
  add(a, b);
}
EOF
)
export stdout=$(cat << EOF
ASSEMBLY:
EXTERN       exit
GLOBAL       _start
SETLABEL     _start
INST         DECSP
INSTRELLABEL CALLR main
INST         POPA
INSTLABEL    CALL exit
SETLABEL     add
INST         DECSP
INST         DECSP
INST         SP_A
INST         A_B
INSTHEX2     RAM_A 0x0002
INST         SUM
INST         A_B
INSTHEX2     RAM_A 0x0002
INST         SUM
INST         A_B
INST         rB_A
INST         PUSHA
INSTHEX      RAM_AL 0x02
INST         SUB
INST         A_B
INST         rB_A
INST         PUSHA
INST         SP_A
INST         A_B
INSTHEX2     RAM_A 0x000E
INST         SUM
INST         A_SP
INST         SP_A
INST         A_B
INSTHEX2     RAM_B 0x000A
INST         SUB
INST         A_B
INST         rB_A
INST         PUSHA
INSTHEX      RAM_AL 0x02
INST         SUB
INST         A_B
INST         rB_A
INST         PUSHA
INST         DECSP
INST         RET
SETLABEL     main
INST         DECSP
INST         DECSP
INST         DECSP
INST         DECSP
INST         SP_A
INST         A_B
INSTHEX2     RAM_A 0x0002
INST         SUM
INST         A_B
INSTHEX2     RAM_A 0x0002
INST         SUM
INST         A_B
INST         rB_A
INST         PUSHA
INSTHEX      RAM_AL 0x02
INST         SUB
INST         A_B
INST         rB_A
INST         PUSHA
INST         SP_A
INST         A_B
INSTHEX2     RAM_A 0x000A
INST         SUM
INST         A_B
INSTHEX2     RAM_A 0x0002
INST         SUM
INST         A_B
INST         rB_A
INST         PUSHA
INSTHEX      RAM_AL 0x02
INST         SUB
INST         A_B
INST         rB_A
INST         PUSHA
INST         DECSP
INST         DECSP
INSTRELLABEL CALLR add
INST         SP_A
INST         A_B
INSTHEX2     RAM_A 0x0014
INST         SUM
INST         A_SP
INST         RET
EOF
)
export params="-D com"
export exitcode=0

#./simpleC $params -e "$prog"

./test $0

